disk:
- type: 'raw'
  path: '../target/disk_deployment.raw'
  size_mib: 512
dirs:
- path: '/usr/etc/apache2'
  uid: 10
  permissions: 0o700
- path: '/usr/etc/apache2/conf-enabled'
  uid: 10
  permissions: 0o700
- path: '/usr/etc/apache2/mods-enabled'
  uid: 10
  permissions: 0o700
- path: '/usr/etc/apache2/sites-enabled'
  uid: 10
  permissions: 0o700
- path: '/usr/www'
  uid: 10
  permissions: 0o700
- path: '/usr/www/html'
  uid: 10
  permissions: 0o700
files:
- source: 'init.yaml'
  destination: '/usr/etc/init.yaml'
  uid: 0
  permissions: 0o400
- source: 'auditd.rules'
  destination: '/usr/etc/auditd/auditd.rules'
  uid: 1
  permissions: 0o400
- source: 'log4rs.json'
  destination: '/usr/etc/auditd/log4rs.json'
  uid: 1
  permissions: 0o400

# Copy apache2 configurations
- source: './apache2/*'
  destination: '/usr/etc/apache2/'
  uid: 10
  permissions: 0o400
- source: './apache2/conf-enabled/*'
  destination: '/usr/etc/apache2/conf-enabled/'
  uid: 10
  permissions: 0o400
- source: './apache2/mods-enabled/*'
  destination: '/usr/etc/apache2/mods-enabled/'
  uid: 10
  permissions: 0o400
- source: './apache2/sites-enabled/*'
  destination: '/usr/etc/apache2/sites-enabled/'
  uid: 10
  permissions: 0o400

# Copy the web page
- source: '../www/*'
  destination: '/usr/www/html'
  uid: 10
  permissions: 0o400
